// db-schemas/*.sql dosyalarini ada gore (dogal sirayla) birlestirip _combined.sql uretir.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SCHEMA_DIR, schemaFiles, readSchemaFile } from './lib/schema-files.mjs';

const files = schemaFiles();
const out = [`-- AUTO-GENERATED by scripts/build-schema.js. ELLE DUZENLEME.`, ...files.map((f) => `\n-- ===== ${f} =====\n${readSchemaFile(f)}`)];
writeFileSync(join(SCHEMA_DIR, '_combined.sql'), `${out.join('\n')}\n`);
console.log(`_combined.sql uretildi (${files.length} dosya: ${files.join(', ')})`);
