// db-schemas/*.sql dosyalarini ada gore (dogal sirayla) birlestirip _combined.sql uretir.
// Girmeyenler: migrations/, "A" ile baslayanlar (elle/superuser), _combined.sql'in kendisi.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'db-schemas');
// Sabit karsilastirma: host locale'i sirayi degistirmesin.
const collator = new Intl.Collator('en', { numeric: true });

const files = readdirSync(dir, { withFileTypes: true })
  .filter((d) => d.isFile() && d.name.endsWith('.sql') && !d.name.startsWith('A') && d.name !== '_combined.sql')
  .map((d) => d.name)
  .sort(collator.compare);

const out = [`-- AUTO-GENERATED by scripts/build-schema.js. ELLE DUZENLEME.`, ...files.map((f) => `\n-- ===== ${f} =====\n${readFileSync(join(dir, f), 'utf8')}`)];
writeFileSync(join(dir, '_combined.sql'), `${out.join('\n')}\n`);
console.log(`_combined.sql uretildi (${files.length} dosya: ${files.join(', ')})`);
